### ISSUE TITLE
Offset/Limit support

### ISSUE THREAD

**Issue by fbjork** [drewolson/scrivener#13]
Any chance we could get offset and limit support added?

**Comment by drewolson** [comment]
Is there something these attributes would provide that `page` and `page_size` don't currently provide? Are they just aliases?

**Comment by fbjork** [comment]
@drewolson page_size is an alias, but offset would have to be calculated every time. 

offset would be page - 1 * page_size. 

Not hard to do, but would be nice to have the option to chose pagination style.

**Comment by drewolson** [comment]
@fbjork I've toyed around with the idea a bit, but it seems to be pretty orthogonal to the current way we're preforming pagination. Perhaps there could be a different function added to the repository responsible for this, something like `window`? If you're interesting, I'd like to see a PR so that I can have a more concrete discussion about it.

**Comment by drewolson** [comment]
Closing this for now, please open a PR if you'd like to continue the discussion.
